namespace Haley.Enums {
    public enum StorageParseMode {
       Parse =0, //UN MANAGED ( IT CAN PARSE AND STORE BUT THE INFORMATION IS NOT STORED IN THE DATABASE, IT EXPECTS YOU TO STORE IT)
       Generate = 1, //MANAGED (ONLY GENERATED BY THE SYSTEM)
       //ParseOrGenerate = 2// Try to parse, if it doesn't work, create it. //Let us not overcomplicate this.. Either the input is sent or generated. Keep it simple.
    }
}
